version=0.1

[default.deploy.parameters]
stack_name = "infra-adm-resources"

[prod.deploy.parameters]
stack_name = "infra-adm-resources"
parameter_overrides = [
    "env=prod"
]

[test.deploy.parameters]
stack_name = "infra-adm-resources"
parameter_overrides = [
    "env=test"
]

[develop.deploy.parameters]
stack_name = "infra-adm-resources"
parameter_overrides = [
    "env=develop"
]





