AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example of processing messages on an SQS queue with Lambda

Parameters:
  env:
    Type: 'String'
    AllowedValues:
      - develop
      - test
      - prod

Resources:
  AdmApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'adm-gateway'
      Description: 'ADM API Gateway'
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 'execute-api:Invoke'
            Resource: 'execute-api:*:*:*/*'
      EndpointConfiguration:
        Types:
          - 'PRIVATE'

  AdmApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref AdmApiGateway
      Description: 'Deployment'
    DependsOn: AdmApiGateway

  AdmApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref env
      RestApiId: !Ref AdmApiGateway
      DeploymentId: !Ref AdmApiGatewayDeployment



